before_install: 'git submodule update --init'
script: 'bundle exec rake test:travis'

env:
  - 'RESTMORE=rest-more'
  - 'RESTMORE=rails2'
  - 'RESTMORE=rails3'

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
